name: NaturalBounties
version: '${project.version}'
main: me.naturalsmp.NaturalBounties.NaturalBounties
api-version: 1.13
authors: [ NaturalDev ]
description: kill...
folia-supported: true
softdepend:
  - PlaceholderAPI
  - HeadDataBase
  - Vault
  - LiteBans
  - SkinsRestorer
  - BetterTeams
  - Towny
  - Geyser-Spigot
  - floodgate
  - Kingdoms
  - Lands
  - WorldGuard
  - Factions
  - Essentials
  - MythicLib
  - Duels
  - SimpleClans
  - packetevents
  - Skript
  - Konquest
commands:
  NaturalBounties:
    description: Use all of the bounty commands.
  NaturalBountiesadmin:
    description: Open the GUI for other people.
    aliases:
      - bountyadmin
permissions:
  NaturalBounties.admin:
    default: op
    description: Remove or edit bounties.
    children: [NaturalBounties.cleanEntities]
  NaturalBounties.cleanentities:
    default: op
    description: Use the command /bounty cleanEntities (radius)
  NaturalBounties.set:
    default: true
    description: Set bounties.
  NaturalBounties.view:
    default: true
    description: View bounties and the bounty GUI.
  NaturalBounties.stats:
    default: true
    description: View your player stats and the leaderboard.
  NaturalBounties.buyown:
    default: true
    description: Buy your own bounty.
  NaturalBounties.immune:
    default: false
    description: Immune to having bounties set on them.
  NaturalBounties.buyimmunity:
    default: true
    description: Buy immunity.
  NaturalBounties.removeimmunity:
    default: true
    description: Remove own immunity.
  NaturalBounties.tracker:
    default: true
    description: Use a bounty tracker.
  # These tracker and poster perms override the settings in display.yml
  NaturalBounties.spawntracker:
    default: false
    description: Spawn in a bounty tracker.
  NaturalBounties.writeemptytracker:
    default: false
    description: Write a bounty into an empty tracker.
  NaturalBounties.washtracker:
    default: false
    description: Wash a bounty tracker.
  NaturalBounties.crafttracker:
    default: false
    description: Craft a bounty tracker.
  NaturalBounties.postertracking:
    default: false
    description: Click on a poster with an empty tracker to track it.
  NaturalBounties.spawnposter:
    default: false
    description: Spawn in a bounty poster.
  NaturalBounties.washposter:
    default: false
    description: Wash a bounty poster.
  NaturalBounties.craftposter:
    default: false
    description: Craft a bounty poster.
  NaturalBounties.writeposter:
    default: false
    description: Write a bounty poster to an empty map.
  NaturalBounties.whitelist:
    default: true
    description: Whitelist players to claim your bounty.
  NaturalBounties.basic:
    default: true
    description: Use help, tutorial, and broadcast commands.
    children:
      NaturalBounties.basic.tutorial: true
  NaturalBounties.basic.tutorial:
    default: true
    description: Use the tutorial command.
  NaturalBounties.removeset:
    default: false
    description: Remove bounties you set.
  NaturalBounties.challenges:
    default: true
    description: View bounty challenges.
  NaturalBounties.claim:
    default: true
    description: Claim a bounty.
  NaturalBounties.player:
    description: All the basic player permissions.
    children:
      - NaturalBounties.set
      - NaturalBounties.view
      - NaturalBounties.buyown
      - NaturalBounties.buyimmunity
      - NaturalBounties.removeimmunity
      - NaturalBounties.tracker
      - NaturalBounties.whitelist
      - NaturalBounties.basic
      - NaturalBounties.challenges
      - NaturalBounties.stats
      - NaturalBounties.claim
      - NaturalBounties.sort
  NaturalBounties.immunity.murder:
    default: false
    description: Immune to murder auto-bounties.
  NaturalBounties.immunity.random:
    default: false
    description: Immune to random auto-bounties.
  NaturalBounties.immunity.timed:
    default: false
    description: Immune to timed auto-bounties.
  NaturalBounties.hunt:
    default: true
    description: Allow players to use the bounty hunt feature.
    children:
      - NaturalBounties.hunt.start
      - NaturalBounties.hunt.participate
  NaturalBounties.hunt.start:
    default: true
    description: Start a bounty hunt.
  NaturalBounties.hunt.participate:
    default: true
    description: Join or leave a bounty hunt.
  NaturalBounties.sort:
    default: true
    description: Sort guis.
libraries:
  - com.mysql:mysql-connector-j:9.4.0
  - io.lettuce:lettuce-core:7.2.1.RELEASE
